name: maccms
services:
    maccms:
        container_name: maccms
        image: esme518/docker-maccms10:latest
        ports:
            - target: 80
              published: "8765"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /home/orangepi/maccms
              target: /var/www/html
        x-casaos:
            ports:
                - container: "80"
                  description:
                    en_us: Web HTTP Port
                    zh_cn: Web HTTP端口
            volumes:
                - container: /var/www/html
                  description:
                    en_us: maccms config directory.
                    zh_cn: maccms 配置目录
    maccms-db:
        container_name: maccms-db
        environment:
            MARIADB_ROOT_PASSWORD: maccms_db_password
        image: mariadb:10.3
        restart: unless-stopped
        volumes:
            - type: bind
              source: /home/orangepi/maccms-db
              target: /var/lib/mysql
        x-casaos:
            volumes:
                - container: /var/lib/mysql
                  description:
                    en_us: maccms-db config directory.
                    zh_cn: maccms-db 配置目录
x-casaos:
    architectures:
        - amd64
        - arm
        - arm64
    author: asxs
    category: myappstore
    icon: https://magicblack.github.io/favicon.ico
    index: /cmsadmin.php
    port_map: "8765"
    scheme: http
    title:
        custom: maccms
        en_us: maccms
