name: maccms
services:
    maccms:
        container_name: maccms
        image: esme518/docker-maccms10:latest
        ports:
            - target: 80
              published: "8765"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /home/orangepi/maccms
              target: /var/www/html
    maccms-db:
        container_name: maccms-db
        environment:
            MARIADB_ROOT_PASSWORD: maccms_db_password
        image: mariadb:10.3
        restart: unless-stopped
        volumes:
            - type: bind
              source: /home/orangepi/maccms-db
              target: /var/lib/mysql
x-casaos:
    author: asxs
    category: myappstore
    icon: https://magicblack.github.io/favicon.ico
    index: /cmsadmin.php
    port_map: "8765"
    scheme: http
    title:
        custom: maccms
        en_us: maccms
