name: locyanfrp
services:
    locyanfrp:
        command:
            - -c
            - /conf/frpc.json
        container_name: locyanfrp
        image: locyanfrp:0.3
        restart: unless-stopped
        volumes:
            - type: bind
              source: /home/orangepi/LoCyanFrp/run
              target: /conf
        x-casaos:
            volumes:
                - container: /conf
                  description:
                    en_us: locyanfrp config directory.
                    zh_cn: locyanfrp 配置目录
x-casaos:
    architectures:
        - arm64
    author: asxs
    category: myappstore
    description:
        zh_cn: null
    developer: asxs
    hostname: ""
    icon: https://www.locyanfrp.cn/favicon.ico
    main: locyanfrp
    port_map: ""
    scheme: http
    tips: null
    title:
        custom: locyanfrp
        en_us: locyanfrp
