name: my-nginx
services:
    nginx:
        container_name: nginx
        image: nginx:stable
        ports:
            - target: 8001
              published: "8001"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: /home/orangepi/nginx
              target: /etc/nginx
            - type: bind
              source: /home/orangepi/nginx/log
              target: /var/log/nginx
        x-casaos:
            ports:
                - container: "8001"
                  description:
                    en_us: Web HTTP Port
                    zh_cn: Web HTTP端口
            volumes:
                - container: /nginx/config
                  description:
                    en_us: nginx config directory.
                    zh_cn: nginx 配置目录
x-casaos:
    architectures:
        - amd64
        - arm
        - arm64
    author: asxs
    category: myappstore
    description:
        zh_cn: nginx 是一个高性能的 HTTP 和反向代理 web 服务器，同时也提供了 IMAP/POP3/SMTP 服务 。
    developer: nginx
    icon: https://nginx.org/favicon.ico
    main: nginx
    port_map: "8001"
    scheme: http
    tagline:
        zh_cn: 一个高性能的 HTTP 和反向代理 web 服务器
    tips: null
    title:
        custom: ""
        en_us: nginx
